name: flutter_form
description: A new Flutter package project.
version: 1.0.0
homepage: https://authnull.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  plugin:
    androidPackage: com.authnull.flutter_form
    pluginClass: FlutterFormPlugin
